stages:
  - 🚦 test
  - 📦 package
  - 🚀 deploy

##############################
#        🚦 TEST 🚦         #
##############################

🚦 lint:
  stage: 🚦 test
  script:
    - yarn install
    - yarn lint
  tags:
    - docker
  only:
    - merge_requests
  cache:
    paths:
      - node_modules/

🚦 audit:
  stage: 🚦 test
  script:
    - yarn install
    - yarn run audit
  tags:
    - docker
  only:
    - merge_requests
  cache:
    paths:
      - node_modules/

🚦 test build:
  image: node:12
  stage: 🚦 test
  cache:
    paths:
      - node_modules
  script:
    - yarn install
    - yarn export
  tags:
    - docker
  only:
    - merge_requests


##############################
#       📦 PACKAGE 📦        #
##############################

.build:
  stage: 📦 package
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker-compose pull || echo "Container not found"
    - docker build -t $CI_REGISTRY_IMAGE:$CI_ENVIRONMENT_NAME --build-arg NODE_APP_INSTANCE=$CI_ENVIRONMENT_NAME .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:$CI_ENVIRONMENT_NAME
  tags:
    - pp-builder

📦 develop:
  extends: .build
  environment:
    name: develop
    url: https://732-digitalax.pixelplex-test.by/
  only:
    - develop

📦 master:
  extends: .build
  environment:
    name: master
    url: https://732-digitalax.pixelplexlabs.com/
  only:
    - master

📦 prod:
  extends: .build
  environment:
    name: prod
    url: https://marketplace.digitalax.xyz/
  only:
    - tags
    - master

📦 manual.master:
  extends: .build
  environment:
    name: master
    url: https://732-digitalax.pixelplexlabs.com/
  except:
    - tags
    - develop
    - master
  when: manual

# 📦 manual.prod:
#   extends: .build
#   environment:
#     name: prod
#     url: http://digitalax.com/
#   except:
#     - tags
#     - develop
#     - master
#   when: manual


##############################
#       🚀 DEPLOY 🚀        #
##############################

.deploy_pull:
  stage: 🚀 deploy
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker-compose pull

.deploy:
  extends: .deploy_pull
  stage: 🚀 deploy
  script:
    - docker-compose -p 732-digitalax up -d front

.deploy_ipfs:
  extends: .deploy_pull
  stage: 🚀 deploy
  script:
    - docker-compose -p 732-digitalax up ipfs_upload

🚀 develop:
  extends: .deploy
  environment:
    name: develop
    url: https://732-digitalax.pixelplex-test.by/
  tags:
    - pp-new-develop
  only:
    - develop

🚀 master:
  extends: .deploy
  environment:
    name: master
    url: https://732-digitalax.pixelplexlabs.com/
  tags:
    - pp-stage
  only:
    - master

🚀 prod:
  stage: 🚀 deploy
  environment:
    name: prod
    url: https://marketplace.digitalax.xyz/
  tags:
    - pp-builder
  only:
    - tags
    - master
  when: manual
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:$CI_ENVIRONMENT_NAME
    - docker run -i --rm -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -e AWS_REGION
      $CI_REGISTRY_IMAGE:$CI_ENVIRONMENT_NAME /bin/sh -c "
      aws s3 cp /app/out/ s3://${AWS_BUCKET}/ --recursive --cache-control max-age=31536000,s-maxage=31536000;
      aws cloudfront  create-invalidation --distribution-id=${AWS_DISTRIBUTION_ID} --paths /
      "

🚀 develop_ipfs:
  extends: .deploy_ipfs
  environment:
    name: develop
    url: https://732-digitalax.pixelplex-test.by/
  tags:
    - pp-new-develop
  only:
    - develop
  when: manual

🚀 master_ipfs:
  extends: .deploy_ipfs
  environment:
    name: master
    url: https://732-digitalax.pixelplexlabs.com/
  tags:
    - pp-stage
  only:
    - master
  when: manual

🚀 other.master:
  extends: .deploy
  environment:
    name: master
    url: https://732-digitalax.pixelplexlabs.com/
  tags:
    - pp-stage
  except:
    - tags
    - develop
    - master
  when: manual

# 🚀 other.prod:
#   extends: .deploy
#   environment:
#     name: prod
#     url: http://digitalax.com/
#   tags:
#     - todo
#   except:
#     - tags
#     - develop
#     - master
#   when: manual
