import React from 'react'
import Image from 'next/image'
import styles from './page5152.module.scss'

const Page5152 = () => (
  <div className={styles.wrapper}>
    <div className={styles.back}>
      <Image src='/magazine/8/images/5152_back.jpg' width={1920} height={1497} />
    </div>
    <div className={styles.rect1} />
    <div className={styles.rect2} />
    <div className={styles.text1}>
      ideas–where all this value is being generated by individuals brought together by the ethos of
      web3: property rights, user self-sovereignty, and above all, decentralization.
      <br />
      <br />
      It’s not hard to see how things will play out–waves of formerly disgruntled employees are
      breaking the chains that once bound them to the 9-5 grind of soul-destroying wagecuckoldry and
      heading for the greener pastures of web3.
    </div>
    <div className={styles.text2}>
      Consequently, more and more individuals are telling their bosses to stick it after having had
      a taste of the proverbial web3 cherry. That has led to a community of rootless full-time web3
      practitioners bound only by the power of their internet connection to emerge. Some of them
      have made the switch as essentially full-time digital nomads, calling anywhere they are their
      office–physical or virtual, real or metaversal notwithstanding.
      <br />
      <br />
      It’s a veritable exodus driven by the limitless freedom, flexibility, mobility, and abundance
      that the lifestyle promises, and where the creators are justly rewarded for their efforts,
      towards a world where self-sovereignty is the norm rather than the exception.
    </div>
    <div className={styles.image1}>
      <Image src='/magazine/8/images/5152_image1.png' width={1227} height={500} />
    </div>
  </div>
)

export default Page5152
